[package]
name = "fourpaws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
catppuccin = "2.2.0"
glob = "0.3.1"
